// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef score_hh
#define score_hh
#include <FL/Fl.H>
void submitScore(int score, const char* level, const char* name); 
bool checkName(const char* name); 
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Button.H>

class Score {
  int score; 
public:
  Score();
private:
  Fl_Double_Window *win;
public:
  Fl_Box *level;
private:
  Fl_Box *box;
  Fl_Input *name;
  void cb_Submit_i(Fl_Return_Button*, void*);
  static void cb_Submit(Fl_Return_Button*, void*);
  void cb_Chicken_i(Fl_Button*, void*);
  static void cb_Chicken(Fl_Button*, void*);
public:
  void show(int score, const char* level);
};
#endif
