// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "score.hh"
#include <FL/fl_ask.H>
#include <stdio.h>

void Score::cb_Submit_i(Fl_Return_Button*, void*) {
  if(checkName(name->value()))
  fl_message("The name is too short!");
else
{
  submitScore(score, level->label(), name->value());
  win->hide();
};
}
void Score::cb_Submit(Fl_Return_Button* o, void* v) {
  ((Score*)(o->parent()->user_data()))->cb_Submit_i(o,v);
}

void Score::cb_Chicken_i(Fl_Button*, void*) {
  win->hide();
}
void Score::cb_Chicken(Fl_Button* o, void* v) {
  ((Score*)(o->parent()->user_data()))->cb_Chicken_i(o,v);
}

Score::Score() {
  { win = new Fl_Double_Window(312, 185, "Final Score");
    win->user_data((void*)(this));
    { level = new Fl_Box(10, 10, 295, 25, "Level");
      level->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    } // Fl_Box* level
    { box = new Fl_Box(10, 35, 295, 55, "1111111111");
      box->labelfont(1);
      box->labelsize(32);
    } // Fl_Box* box
    { name = new Fl_Input(10, 110, 295, 25, "Enter your name:");
      name->align(FL_ALIGN_TOP_LEFT);
    } // Fl_Input* name
    { Fl_Return_Button* o = new Fl_Return_Button(175, 145, 125, 25, "Submit online");
      o->callback((Fl_Callback*)cb_Submit);
    } // Fl_Return_Button* o
    { Fl_Button* o = new Fl_Button(45, 145, 125, 25, "Chicken out");
      o->callback((Fl_Callback*)cb_Chicken);
    } // Fl_Button* o
    win->set_modal();
    win->end();
  } // Fl_Double_Window* win
}

void Score::show(int score, const char* level) {
  this->score = score;
char buf[32];
snprintf(buf, sizeof(buf), "%d", score);
this->level->copy_label(level);
box->copy_label(buf);
win->show();
}
